version: '1.0'
stages:
  - Builds
steps:
  Builds:
    type: parallel
    stage: Builds
    steps: 
      BuildingDockerImage:
        title: Building Docker Image with goproxy
        type: build
        image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}-proxy'
        dockerfile: Dockerfile
      BuildingDockerImageNoProxy:
        title: Building Docker Image without goproxy
        type: build
        image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}-noproxy'
        dockerfile: Dockerfile.noproxy
