version: '1.0'
stages:
  - build
steps:
  Builds:
    type: parallel
    steps: 
      BuildingDockerImage:
        title: Building Docker Image with goproxy
        type: build
        image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
        dockerfile: Dockerfile
      BuildingDockerImage:
        title: Building Docker Image withou goproxy
        type: build
        image_name: ${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}
        working_directory: ./
        tag: '${{CF_BRANCH_TAG_NORMALIZED}}'
        dockerfile: Dockerfile.noproxy
